name: flutter_tubes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0
  shared_preferences: ^2.2.2

  http: ^0.13.3
  intl: ^0.18.1

flutter:
  uses-material-design: true
